config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :email_addresses, except: [:index, :show]
  resources :phone_numbers, except: [:index, :show]
  resources :people

end

app/models/person.rb
class Person < ActiveRecord::Base
  include Contact
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def to_s
    "#{last_name}, #{first_name}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing <%= @person.first_name %> <%= @person.last_name %></h1>

<%= render 'form' %>

<ul class="actions">
  <li><%= link_to 'Show', @person %> </li>
  <li><%= link_to 'Back', people_path %></li>
</ul>

app/views/people/index.html.erb
<h1>Listing People</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Action</th>
  </tr>

  <% @people.each do |person| %>
    <tr>
      <td><%= person.first_name %></td>
      <td><%= person.last_name %></td>
      <ul>
        <li><%= link_to 'Show', person %></li>
        <li><%= link_to 'Edit', edit_person_path(person) %></li>
        <li><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </tr>
  <% end %>

</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="person">
  <h1><%= @person.first_name %>, <%= @person.last_name %></h1>
  <%= render 'phone_numbers/phone_numbers', phone_numbers: @person.phone_numbers %>

  <%= render 'email_addresses/email_addresses', email_addresses: @person.email_addresses %>

<ul>
  <li><%= link_to 'Add phone number', new_phone_number_path(contact_id: @person.id, contact_type: 'Person') %></li>
  <li><%= link_to 'Add email address', new_email_address_path(contact_id: @person.id, contact_type: 'Person') %></li>
  <li><%= link_to 'Edit', edit_person_path(@person) %></li>
  <li><%= link_to 'Back', people_path %></li>
</ul>

</div>