config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :email_addresses, except: [:index, :show]
  resources :phone_numbers, except: [:index, :show]
  resources :people

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :contact, polymorphic: true
  
  validates :number, :contact_id, presence: true

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:edit, :update, :destroy]

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :contact_id, :contact_type)
    end
end

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>

  <%= f.hidden_field :contact_id %>
  <%= f.hidden_field :contact_type %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/_phone_numbers.html.erb
<ul>
  <% phone_numbers.each do |phone| %>
    <li>
      <%= phone.number %>
      <%= link_to('edit', edit_phone_number_path(phone)) %> | 
      <%= link_to('delete', phone_number_path(phone), method: :delete) %>
    </li>
  <% end %>
</ul>

app/views/phone_numbers/edit.html.erb
<h1><%= "Editing Phone Number for #{@phone_number.contact}" %></h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/new.html.erb
<h1><%= "New Phone Number for #{@phone_number.contact}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path %>