config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :email_addresses, except: [:index, :show]
  resources :phone_numbers, except: [:index, :show]
  resources :people

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :phone_numbers, as: :contact
  has_many :email_addresses, as: :contact
  validates :name, presence: true
  
  def to_s
    "#{name}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing <%= @company.name %></h1>

<%= render 'form' %>

<ul class="actions">
  <li><%= link_to 'Show', @company %></li> 
  <li><%= link_to 'Back', companies_path %></li>
</ul

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td>
      <ul>
        <li><%= link_to 'Show', company %></li>
        <li><%= link_to 'Edit', edit_company_path(company) %></li>
        <li><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path, id: 'new_company' %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="company">
  <h1><%= @company.name %></h1>  

<%= render 'phone_numbers/phone_numbers', phone_numbers: @company.phone_numbers %>

<%= render 'email_addresses/email_addresses', email_addresses: @company.email_addresses %>

<ul>
  <li><%= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company') %></li>
  <li><%= link_to 'Add email address', new_email_address_path(contact_id: @company.id, contact_type: 'Company') %></li>
  <li><%= link_to 'Edit', edit_company_path(@company) %></li>
  <li><%= link_to 'Back', companies_path %></li>
</ul>

</div>